# -*- coding: utf-8 -*-
# Connects an mBot Neo to a Wi-Fi network using credentials from config.yaml
# and displays its IP address on the screen.

# Requires the 'makeblock' and 'PyYAML' libraries.
# Make sure they are installed on your mBot Neo.

# The Wi-Fi SSID and password are read from a 'config.yaml' file
# located in the same directory as the script.

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"