# generated by mBlock5 for CyberPi
# codes make you happy



# 1. Import the required modules
import event
import cyberpi
import random

@event.start
def on_start():
    cyberpi.console.print("Press > to start.")

@event.is_press('b')
def is_btn_press_b():

    if not cyberpi.wifi.is_connect():
        cyberpi.wifi.connect("SSID", "password")
        cyberpi.led.show('blue blue blue blue blue')
    cyberpi.console.println("Connecting to WIFI...")
    while not cyberpi.wifi.is_connect():
      # DO SOMETHING
      pass

    cyberpi.led.show('green green green green green')
    cyberpi.console.print("Connected to WIFI.")

    
    client_id = "mBot_mqtt_client"
    server = "ip_address"
    port = 1883

    topic = "From_mBot"
    data = "Hello Broker, it's me, mBot"
    subscribe_topic = "For_mBot"

    cyberpi.mqtt.set_broker(client_id, server, port)
    is_connected = cyberpi.mqtt.connect()
    if is_connected:
        cyberpi.console.print("Connected to Broker")
        cyberpi.led.show('green blue green blue green')
        cyberpi.mqtt.subscribe_message(subscribe_topic)
        cyberpi.mqtt.set_callback(message_received)
    else:
        cyberpi.console.println("Connect to Broker failed")
        cyberpi.led.show('red red red red red')


def message_received(topic, payload):
    cyberpi.console.print(topic)
    cyberpi.console.print(payload)
    cyberpi.led.show('white white white white white')

@event.is_press('a')
def is_btn_press_a():
    cyberpi.mqtt.off()
    cyberpi.console.print("Disconnected.")
    cyberpi.led.show('black black black black black')
    cyberpi.wifi.disconnect()
    cyberpi.console.print("Disconnected.")
    cyberpi.console.print("Press > to start.")
    cyberpi.console.print("Press [] to stop.")
    cyberpi.console.print("Press ^ to send message.")
    cyberpi.console.print("Press v to receive message.")
     
@event.is_press('up')
def is_btn_press_up():
    topic = "From_mBot"
    data = "Hello Broker, it's me, mBot"
    cyberpi.mqtt.publish_message(topic, data)
    cyberpi.console.print("Message sent.")