# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi

@event.start
def on_start():
    cyberpi.console.print("Press > to start.")

@event.is_press('b')
def is_btn_press():
    

    cyberpi.wifi.connect("PlumLanSp", "pl2um2mp2supl2um2mp2su")
    cyberpi.led.show('blue blue blue blue blue')
    cyberpi.console.println("Connecting...")
    while not cyberpi.wifi.is_connect():
      # DO SOMETHING
      pass

    cyberpi.wifi.disconnect()
    cyberpi.led.show('green green green green green')
    cyberpi.console.print("Connected.")
    cyberpi.console.print("Press [ ] to disconnect")
    while True:
        while not cyberpi.controller.is_press('c'):
            time.sleep(0.1)
            pass
        cyberpi.stop_all()
        cyberpi.wifi.disconnect()
        cyberpi.led.show('blue blue blue blue blue')
        